---
title: "labortech_initialworks"
author: "Pedro Leite"
date: "2023-03-16"
output: pdf_document
---

# Tecnologia e Trabalho

## Este documento será utilizado para os passos iniciais de manipulação de dados da pesquisa acadêmica sobre a ampla relação entre tecnologia e mercado de trabalho. Basicamente, funcionará como um piloto para futuros projetos próprios nesta área.

## Pacotes iniciais:

```{r 1) Pacotes iniciais, echo=FALSE, message=FALSE, warning=FALSE}
library(here) # Ajuda a definir o diretório
library(haven) # Ajuda a ler arquivos dta
library(basedosdados) # Necessário para baixar arquivos do site Base dos dados
library(dplyr) # Pacote fundamental para funções de if else, mutate, group by e etc
library(readr) # Ajuda a ler e converter artigos de diversas formas
```

## Baixando e/ou abrindo os dados

```{r Baixando e/ou abrindo os dados, echo=FALSE, message=FALSE, warning=FALSE}

set_billing_id('trab01industria') # ID do Google Cloud 
download(query = 'SELECT ano, id_municipio, cbo_1994, cbo_2002 FROM `basedosdados.br_me_rais.microdados_vinculos` WHERE ano in (1999)', path = here("data/dadosteste.csv")) # Quais variáveis necessárias, o link de onde baixar e o caminho. 

varnecessarias = read.delim(here("data/dadosteste.csv"), header=T, sep = ",") # Ler a base de dados


```
